<div id="header">
			<div id="header_first">
				<div id="wrapper">
					<div id="header_logo">
						<div id="logo">
							<img src="../img/image.jpg">
						</div>
						<div id="sch">
							<h1>School Name</h1>
						</div>
					</div>
					<div id="Profile">
						<div id="profilePix">
							<a href=""><img src="../img/profile.jpg"></a>
						</div>
						<div id="profileDtl">
							<h1>Welcome uche</h1>
							<ul>
								<li><a href="profile.php">my profile /</a></li>
								<li><a href="">log off /</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div id="header_second">
				<div id="wrapper">
					
				</div>
		</div>
	</div>